apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sentinel
  namespace: g11-bytebazaar
spec:
  serviceName: sentinel
  replicas: 3
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      initContainers:
      - name: config
        image: redis:7.2.4
        command: [ "sh", "-c" ]
        args:
          - |
            nodes=redis-0.redis,redis-1.redis,redis-2.redis
            loop=$(echo $nodes | sed -e "s/,/\n/g")

            for i in $loop
            do
              echo "finding master at $i"
              MASTER=$(redis-cli --no-auth-warning --raw -h $i info replication | awk '{print $1}' | grep master_host: | cut -d ":" -f2)
              if [ "$MASTER" = "" ]; then
                  echo "no master found"
              else
                  echo "found $MASTER"
                  break
              fi
            done
            echo "sentinel monitor mymaster $MASTER 6379 2" >> /tmp/master
            echo "port 5000
            sentinel resolve-hostnames yes
            sentinel announce-hostnames yes
            $(cat /tmp/master)
            sentinel down-after-milliseconds mymaster 5000
            sentinel failover-timeout mymaster 60000
            sentinel parallel-syncs mymaster 1
            " > /etc/redis/sentinel.conf
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/

      containers:
      - name: sentinel
        image: redis:7.0.10-alpine
        command: ["redis-sentinel"]
        args: ["/etc/redis/sentinel.conf"]
        ports:
        - containerPort: 5000
          name: sentinel
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: redis-config
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel
  namespace: g11-bytebazaar
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: sentinel
  clusterIP: None
