---
apiVersion: apps/v1
#kind: DaemonSet
#kind: ReplicaSet
kind: Deployment
metadata:
  name: app
  namespace: a108840
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
        course: gic
        year: "2024"
    spec:
      containers:
      - name: app
        image: registry.deti/a108840/app:v1
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
