apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-configs
  namespace: g11-bytebazaar
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins:
                - "https://bytebazaar.k3s"
                - "http://bytebazaar.k3s"

    processors:
      batch:
        timeout: 10s
    
    exporters:
      otlp/jaeger:
        endpoint: "jaeger-collector:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"
        enable_open_metrics: true
      logging:
        loglevel: debug
    
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger, logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, logging]

  prometheus-config.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: (.+):(.+)
            replacement: ${1}:$(2)
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
      
      - job_name: 'otel-collector'
        static_configs:
          - targets: ['otel-collector.g11-bytebazaar.svc.cluster.local:8889'] # Scrape OTel Collector's Prometheus exporter

  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true

      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger-collector:16686
        editable: true