apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: g11-bytebazaar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.56
        ports:
          - containerPort: 4317
            protocol: TCP
          - containerPort: 5778 
            protocol: TCP
          - containerPort: 6831
            protocol: TCP
          - containerPort: 6832
            protocol: TCP
          - containerPort: 14250
            protocol: TCP
          - containerPort: 16686
            protocol: TCP
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: g11-bytebazaar
spec:
  selector:
    app: jaeger
  ports:
    - name: grpc
      protocol: TCP
      port: 4317
    - name: http
      protocol: TCP
      port: 14250
    - name: thrift
      protocol: TCP
      port: 14268
    - name: thrift-compact
      protocol: TCP
      port: 16686
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui
  namespace: g11-bytebazaar
spec:
  selector:
    app: jaeger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 16686
  type: ClusterIP
    

