# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /etc/docker/certs.d/registry.deti
    echo '{"default-address-pools": [{"base":"10.139.0.0/16","size":24}]}' > /etc/docker/daemon.json
    openssl s_client -connect 193.136.82.36:443 -showcerts -servername registry.deti </dev/null 2>/dev/null|openssl x509 -outform PEM >/etc/docker/certs.d/registry.deti/ca.crt
    if grep -Fxq "registry.deti" /etc/hosts; then
      echo '193.136.82.36 registry.deti' >> /etc/hosts
    fi

    if [ ! -f /etc/apt/keyrings/docker.asc ]; then
      echo 'Docker keyring not found, installing Docker'
      echo 'Cleaning up old Docker installations'
      for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done
      apt-get update
      apt-get install -y ca-certificates curl
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      chmod a+r /etc/apt/keyrings/docker.asc

      echo 'Adding Docker repository'
      echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
      echo 'Installing Docker'
      apt-get update
      apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    fi
    echo 'All done'

  SHELL
end
