apiVersion: apps/v1
kind: Deployment
metadata:
  name: budibase-deployment
  namespace: g11-bytebazaar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budibase
  template:
    metadata:
      labels:
        app: budibase
    spec:
      containers:
        - name: budibase
          image: budibase/budibase:latest
          envFrom:
          - secretRef:
              name: budibase-secrets
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "768Mi"
              cpu: "500m"
            limits:
              memory: "1.5Gi"
              cpu: "900m"
          volumeMounts:
            - name: budibase-data
              mountPath: /data
      volumes:
        - name: budibase-data
          persistentVolumeClaim:
            claimName: budibase-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: budibase-service
  namespace: g11-bytebazaar
spec:
  selector:
    app: budibase
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---